//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServisoClientas.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebServisoClientas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paskaitos rasti nepavyko!.
        /// </summary>
        internal static string ButtonGautiPaskaitaClick_PaskaitosRastiNepavyko {
            get {
                return ResourceManager.GetString("ButtonGautiPaskaitaClick_PaskaitosRastiNepavyko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paskaita pridėta sėkmingai.
        /// </summary>
        internal static string ButtonPridetiClick_PaskaitaPridėtaSekmingai {
            get {
                return ResourceManager.GetString("ButtonPridetiClick_PaskaitaPridėtaSekmingai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paskaitos pridėti nepavyko.
        /// </summary>
        internal static string ButtonPridetiClick_PaskaitosPridetiNepavyko {
            get {
                return ResourceManager.GetString("ButtonPridetiClick_PaskaitosPridetiNepavyko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepavyko priskirti paskaitos studentui!.
        /// </summary>
        internal static string ButtonPriskirtiClick_NepavykoPriskirtiPaskaitos {
            get {
                return ResourceManager.GetString("ButtonPriskirtiClick_NepavykoPriskirtiPaskaitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paskaita sėkmingai priskirta studentui.
        /// </summary>
        internal static string ButtonPriskirtiClick_PaskaitaPriskirtaStudentui {
            get {
                return ResourceManager.GetString("ButtonPriskirtiClick_PaskaitaPriskirtaStudentui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įvesti paskaitos kodą privaloma!.
        /// </summary>
        internal static string TextBoxInsertPaskaitosKodasValidating_KodasPrivalomas {
            get {
                return ResourceManager.GetString("TextBoxInsertPaskaitosKodasValidating_KodasPrivalomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Įvesti pavadinimą privaloma!.
        /// </summary>
        internal static string TextBoxInsertPaskaitosKodasValidating_PavadinimasPrivalomas {
            get {
                return ResourceManager.GetString("TextBoxInsertPaskaitosKodasValidating_PavadinimasPrivalomas", resourceCulture);
            }
        }
    }
}
